"""scripts/progress.py

Computes real-time completion percentage per project part by counting how
many of the original scaffold's `raise NotImplementedError("Part X: ...")`
stub markers have been removed (i.e. implemented) in the current tree.

Baseline counts are fixed at the number of stub markers present in the
initial scaffold commit (cdda399) and must not be changed here even as
stubs get implemented -- they are the denominator, not a moving target.

Run manually:
    python3 scripts/progress.py

Also run automatically on every push via .github/workflows/progress.yml,
which commits the regenerated PROGRESS.md back to the repo so the tracker
stays current with zero manual upkeep.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent

# Fixed denominators: number of `NotImplementedError("Part X: ...")` stub
# markers present in the original scaffold commit for each part. Do not
# adjust these as stubs get implemented -- see module docstring.
BASELINE = {
    "A": {"label": "Data Export Layer", "owner": "you", "total": 3},
    "B": {"label": "AI Classification", "owner": "Rajesh", "total": 12},
    "C": {"label": "Playlist Logic + Write-back", "owner": "you", "total": 4},
    "D": {"label": "GUI + Web App Design", "owner": "Rajesh", "total": 7},
}

STUB_PATTERN = re.compile(r'NotImplementedError\("Part ([A-D])')


def count_remaining_stubs() -> dict[str, int]:
    """Grep the current tree for remaining NotImplementedError stubs per part."""
    remaining = {part: 0 for part in BASELINE}
    for py_file in REPO_ROOT.rglob("*.py"):
        if "scripts" in py_file.parts:
            continue
        text = py_file.read_text(encoding="utf-8", errors="ignore")
        for match in STUB_PATTERN.finditer(text):
            remaining[match.group(1)] += 1
    return remaining


def build_report() -> dict:
    remaining = count_remaining_stubs()
    parts = {}
    total_done = 0
    total_all = 0
    for part, info in BASELINE.items():
        total = info["total"]
        left = remaining.get(part, 0)
        done = max(total - left, 0)
        pct = round(100 * done / total) if total else 100
        parts[part] = {
            "label": info["label"],
            "owner": info["owner"],
            "done": done,
            "total": total,
            "percent": pct,
        }
        total_done += done
        total_all += total
    overall_pct = round(100 * total_done / total_all) if total_all else 0
    return {"parts": parts, "overall_percent": overall_pct}


def bar(pct: int, width: int = 20) -> str:
    filled = round(width * pct / 100)
    return "#" * filled + "-" * (width - filled)


def render_markdown(report: dict) -> str:
    lines = [
        "# Playlist AI -- Progress",
        "",
        f"**Overall: {report['overall_percent']}% complete**",
        "",
        "| Part | Owner | Progress | % |",
        "|------|-------|----------|---|",
    ]
    for part, data in report["parts"].items():
        lines.append(
            f"| {part} -- {data['label']} | {data['owner']} "
            f"| `{bar(data['percent'])}` ({data['done']}/{data['total']}) "
            f"| {data['percent']}% |"
        )
    lines.append("")
    lines.append(
        "_Auto-generated by `scripts/progress.py` on every push -- do not edit by hand._"
    )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    report = build_report()
    (REPO_ROOT / "progress.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    (REPO_ROOT / "PROGRESS.md").write_text(render_markdown(report), encoding="utf-8")
    print(render_markdown(report))


if __name__ == "__main__":
    main()
